TOP_SRCDIR = ..
include $(TOP_SRCDIR)/Makefile.common

# Prevent deletion of intermediate files, e.g. cat.o, after first build, so
# that disk image changes after first build are persistent until clean.  More
# details:
# http://www.gnu.org/software/make/manual/html_node/Chained-Rules.html
.PRECIOUS: %.o

UPROGS=\
	_cat\
	_echo\
	_forktest\
	_grep\
	_init\
	_kill\
	_ln\
	_ls\
	_mkdir\
	_rm\
	_sh\
	_stressfs\
	_usertests\
	_wc\
	_zombie

all: ../lib/ulib.a $(UPROGS)
	mv _* ..

../lib/ulib.a:
	$(MAKE) -C ../lib ulib.a

_%: %.o ../lib/ulib.a
	$(LD) $(LDFLAGS) -N -e main -Ttext 0 -o $@ $^
	$(OBJDUMP) -S $@ > $*.asm
	$(OBJDUMP) -t $@ | sed '1,/SYMBOL TABLE/d; s/ .* / /; /^$$/d' > $*.sym

_forktest: forktest.o $(ULIB)
	# forktest has less library code linked in - needs to be small
	# in order to be able to max out the proc table.
	$(LD) $(LDFLAGS) -N -e main -Ttext 0 -o _forktest forktest.o ../lib/ulib.o ../lib/usys.o
	$(OBJDUMP) -S _forktest > forktest.asm


clean:
	rm -f _* *.asm *.o *.sym *.d
