.Dd July 31, 2016
.Dt LS 1
.Os
.Sh NAME
.Nm ls
.Nd list directory contents.
.Sh SYNOPSIS
.Nm ls
.Op Fl dial
.Op Ar file ...
.Sh DESCRIPTION
For each operand that names a
.Ar file
of a type other than
directory,
.Nm ls
displays its name as well as any requested,
associated information.
For each operand that names a
.Ar file
of type directory,
.Nm ls
displays the names of files contained
within that directory, as well as any requested, associated
information.
.Pp
If no operands are given, the contents of the current
directory are displayed.
If more than one operand is given,
non-directory operands are displayed first; directory
and non-directory operands are sorted separately and in
lexicographical order.
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl a
Include directory entries whose names begin with a
dot (.).
.It Fl d
Directories are listed as plain files (not searched recursively).
.It Fl i
For each file, print the file's file serial number (inode number).
.It Fl l
(The lowercase letter ``ell.'')  List in long format.
.Ss The Long Format
If the
.Fl l
option is given, the following information
is be displayed:
file mode,
number of links, owner name,
.\" group name,
number of bytes in the file, abbreviated
month, day-of-month file was last modified,
hour file last modified, minute file last
modified, and the pathname.
.Sh HISTORY
A
.Nm ls
command appeared in
.At v6 .
