TOP_SRCDIR = ../..
include $(TOP_SRCDIR)/Makefile.common
CFLAGS+=-D_CURSES_PRIVATE

all: addbytes.o addch.o addnstr.o box.o clear.o clrtobot.o clrtoeol.o cr_put.o ctrace.o cur_hash.o curses.o delch.o deleteln.o delwin.o erase.o fullname.o getch.o getstr.o id_subwins.o idlok.o initscr.o insch.o insertln.o longname.o move.o mvwin.o newwin.o overlay.o overwrite.o printw.o putchar.o refresh.o scanw.o scroll.o setterm.o standout.o toucholap.o touchwin.o tscroll.o tstp.o tty.o unctrl.o

clean:
	rm -f *.o
