TOP_SRCDIR = ../..
include $(TOP_SRCDIR)/Makefile.common

all: _rand48.o abort.o abs.o atexit.o atof.o atoi.o atol.o bsearch.o calloc.o div.o drand48.o erand48.o exit.o getenv.o getopt.o heapsort.o jrand48.o labs.o lcong48.o ldiv.o lrand48.o malloc.o mrand48.o nrand48.o putenv.o rand.o random.o seed48.o setenv.o srand48.o strtod.o strtol.o strtoul.o system.o qsort.o

clean:
	rm -f *.o
